OgrenciSistemiMVC/OgrenciSistemiMVC/Models/Ogrenci.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
    
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> OgrenciNo { get; set; }
        public Nullable<System.DateTime> DTarih { get; set; }
        public string Bolum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
}

OgrenciSistemiMVC/OgrenciSistemiMVC/Controllers/OgrenciController.cs
using OgrenciSistemiMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OgrenciSistemiMVC.Controllers
{
    public class OgrenciController : Controller
    {
        // GET: Ogrenci
        DbOgrenciYonetimiEntities db = new DbOgrenciYonetimiEntities();
        public ActionResult Index()
        {
            var ogrenciler = db.Ogrenci.ToList();
            return View(ogrenciler);
        }

        [HttpGet]
        public ActionResult OgrenciEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult OgrenciEkle(Ogrenci t)
        {
            db.Ogrenci.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult OgrenciSil(int id)
        {
            var ogrenci = db.Ogrenci.Find(id);
            db.Ogrenci.Remove(ogrenci);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult OgrenciGetir(int id)
        {
            var ogrenci = db.Ogrenci.Find(id);
            return View("OgrenciGetir", ogrenci);
        }

        public ActionResult OgrenciGuncelle(Ogrenci t)
        {
            var ogrenci = db.Ogrenci.Find(t.Id);
            ogrenci.AdSoyad = t.AdSoyad;
            ogrenci.KayitTarih = t.KayitTarih;
            ogrenci.OgrenciNo = t.OgrenciNo;
            ogrenci.DTarih = t.DTarih;
            ogrenci.Bolum = t.Bolum;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

OgrenciSistemiMVC/OgrenciSistemiMVC/Views/Ogrenci/Index.cshtml
@using OgrenciSistemiMVC.Models;
@model List<Ogrenci>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:25px">
    <tr>
        <th>ID</th>
        <th>Ad Soyad</th>
        <th>Kayıt Tarihi</th>
        <th>Öğrenci Numarası</th>
        <th>Doğum Tarihi</th>
        <th>Bölümü</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Id</td>
            <td>@x.AdSoyad</td>
            <td>@x.KayitTarih</td>
            <td>@x.OgrenciNo</td>
            <td>@x.DTarih</td>
            <td>@x.Bolum</td>
            <td><a href="/Ogrenci/OgrenciSil/@x.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Ogrenci/OgrenciGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
        </tr>

    }
</table>
<a href="/Ogrenci/OgrenciEkle" class="btn btn-primary">Yeni Öğrenci</a>

OgrenciSistemiMVC/OgrenciSistemiMVC/Views/Ogrenci/OgrenciEkle.cshtml
@model OgrenciSistemiMVC.Models.Ogrenci
@{
    ViewBag.Title = "OgrenciEkle";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<h2 style="margin-top:25px">Ogrenci Ekle</h2>
<br />
<form class="form-group" method="post">
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.AdSoyad)
        @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.KayitTarih)
        @Html.TextBoxFor(x => x.KayitTarih, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciNo)
        @Html.TextBoxFor(x => x.OgrenciNo, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.DTarih)
        @Html.TextBoxFor(x => x.DTarih, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Bolum)
        @Html.TextBoxFor(x => x.Bolum, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Kaydet</button>
</form>

OgrenciSistemiMVC/OgrenciSistemiMVC/Views/Ogrenci/OgrenciGetir.cshtml
@model OgrenciSistemiMVC.Models.Ogrenci
@{
    ViewBag.Title = "OgrenciGetir";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<h2 style="margin-top:25px" >Ogrenci Getir</h2>

@using (Html.BeginForm("OgrenciGuncelle", "Ogrenci", FormMethod.Post))
{
    <div style="margin-bottom: 15px">
        @Html.HiddenFor(y => y.Id)
        @Html.LabelFor(x => x.AdSoyad)
        @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.KayitTarih)
        @Html.TextBoxFor(x => x.KayitTarih, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OgrenciNo)
        @Html.TextBoxFor(x => x.OgrenciNo, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.DTarih)
        @Html.TextBoxFor(x => x.DTarih, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Bolum)
        @Html.TextBoxFor(x => x.Bolum, new { @class = "form-control" })
    </div>
    <button class="btn btn-success">Güncelle</button>
}