OgrenciSistemiMVC/OgrenciSistemiMVC/Models/Ders.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ders()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }

    
        public int Id { get; set; }
        public string Ad { get; set; }
        public Nullable<byte> Kredi { get; set; }
        public Nullable<int> OkulYonetimId { get; set; }
        public string DersRenk { get; set; }
    
        public virtual Personal Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
}

OgrenciSistemiMVC/OgrenciSistemiMVC/Controllers/DersController.cs
using OgrenciSistemiMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace OgrenciSistemiMVC.Controllers
{
    public class DersController : Controller
    {
        // GET: Ders
        DbOgrenciYonetimiEntities db = new DbOgrenciYonetimiEntities();
        public ActionResult Index()
        {
            var ders = db.Ders.ToList();
            return View(ders);
        }

        [HttpGet]
        public ActionResult DersEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DersEkle(Ders ders)
        {
            db.Ders.Add(ders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DersSil(int id)
        {
            var ders = db.Ders.Find(id);
            db.Ders.Remove(ders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DersGetir(int id)
        {
            var ders = db.Ders.Find(id);
            return View("DersGetir", ders);
        }

        public ActionResult DersGuncelle(Ders t)
        {
            var ders = db.Ders.Find(t.Id);
            ders.Ad = t.Ad;
            ders.Kredi = t.Kredi;
            ders.OkulYonetimId = t.OkulYonetimId;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

OgrenciSistemiMVC/OgrenciSistemiMVC/Views/Ders/DersEkle.cshtml
@model OgrenciSistemiMVC.Models.Ders
@{
    ViewBag.Title = "DersEkle";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<h2 style="margin-top:25px">Ders Ekle</h2>
<form class="form-group" method="post">
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Ad)
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Kredi)
        @Html.TextBoxFor(x => x.Kredi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.OkulYonetimId)
        @Html.TextBoxFor(x => x.OkulYonetimId, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.DersRenk,"Ders Rengi(RGB(0,0,0))")
        @Html.TextBoxFor(x => x.DersRenk, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Kaydet</button>
</form>

OgrenciSistemiMVC/OgrenciSistemiMVC/Views/Ders/DersGetir.cshtml
@model OgrenciSistemiMVC.Models.Ders
@{
    ViewBag.Title = "DersGetir";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<h2 style="margin-top:25px">Ders Getir</h2>

@using (Html.BeginForm("DersGuncelle", "Ders", FormMethod.Post))

{
    <form class="form-group" method="post">
        <div style="margin-bottom: 15px">
            @Html.HiddenFor(y => y.Id)
            @Html.LabelFor(x => x.Id)
            @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
        </div>
        <div style="margin-bottom: 15px">
            @Html.LabelFor(x => x.Kredi)
            @Html.TextBoxFor(x => x.Kredi, new { @class = "form-control" })
        </div>
        <div style="margin-bottom: 15px">
            @Html.LabelFor(x => x.OkulYonetimId)
            @Html.TextBoxFor(x => x.OkulYonetimId, new { @class = "form-control" })
        </div>
        <div style="margin-bottom: 15px">
            @Html.LabelFor(x => x.DersRenk)
            @Html.TextBoxFor(x => x.DersRenk, new { @class = "form-control" })
        </div>
        <button class="btn btn-success">Güncelle</button>
    </form>
}

OgrenciSistemiMVC/OgrenciSistemiMVC/Views/Ders/Index.cshtml
@using OgrenciSistemiMVC.Models;
@model List<Ders>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:25px">
    <tr>
        <th>ID</th>
        <th>Ders Adı</th>
        <th>Kredisi</th>
        <th>Dersi Veren Kişi</th>
        <th>Sil</th>
        <th>Güncelle</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Id</td>
            <td bgcolor="@x.DersRenk" style="color:white">@x.Ad</td>
            <td>@x.Kredi</td>
            <td>@x.Personal.AdSoyad</td>
            <td><a href="/Ders/DersSil/@x.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Ders/DersGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
        </tr>

    }
</table>
<a href="/Ders/DersEkle" class="btn btn-primary">Yeni Ders</a>