OgrenciSistemiMVC/OgrenciSistemiMVC/Models/Personal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Ders = new HashSet<Ders>();
        }
    
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Gorevi { get; set; }
        public Nullable<int> YonetimTip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ders> Ders { get; set; }
        public virtual OkulYonetimi OkulYonetimi { get; set; }
    }
}

OgrenciSistemiMVC/OgrenciSistemiMVC/Controllers/PersonalController.cs
using OgrenciSistemiMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OgrenciSistemiMVC.Controllers
{
    public class PersonalController : Controller
    {
        // GET: Personal
        DbOgrenciYonetimiEntities db = new DbOgrenciYonetimiEntities();
        public ActionResult Index()
        {
            var personal = db.Personal.ToList();
            return View(personal);
        }

        [HttpGet]
        public ActionResult PersonalEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PersonalEkle(Personal t)
        {
            db.Personal.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonalSil(int id)
        {
            var personal = db.Personal.Find(id);
            db.Personal.Remove(personal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonalGetir(int id)
        {
            var personal = db.Personal.Find(id);
            return View("PersonalGetir", personal);
        }

        public ActionResult PersonalGuncelle(Personal t)
        {
            var personal = db.Personal.Find(t.Id);
            personal.AdSoyad = t.AdSoyad;
            personal.Gorevi = t.Gorevi;
            personal.YonetimTip = t.YonetimTip;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

OgrenciSistemiMVC/OgrenciSistemiMVC/Views/Personal/Index.cshtml
@using OgrenciSistemiMVC.Models;
@model List<Personal>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:25px">
    <tr>
        <th>ID</th>
        <th>Ad Soyad</th>
        <th>Görevi</th>
        <th>Yönetim Tipi</th>
        <th>Sil</th>
        <th>Güncelle</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Id</td>
            <td>@x.AdSoyad</td>
            <td>@x.OkulYonetimi.YonetimTipi</td>
            <td>@x.YonetimTip</td>
            <td><a href="/Personal/PersonalSil/@x.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Personal/PersonalGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
        </tr>

    }
</table>
<a href="/Personal/PersonalEkle" class="btn btn-primary">Yeni Personal</a>

OgrenciSistemiMVC/OgrenciSistemiMVC/Views/Personal/PersonalEkle.cshtml
@model OgrenciSistemiMVC.Models.Personal
@{
    ViewBag.Title = "PersonalEkle";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<h2 style="margin-top:25px">Personal Ekle</h2>

<form class="form-group" method="post">
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.AdSoyad)
        @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.YonetimTip)
        @Html.TextBoxFor(x => x.YonetimTip, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Kaydet</button>
</form>

OgrenciSistemiMVC/OgrenciSistemiMVC/Views/Personal/PersonalGetir.cshtml
@model OgrenciSistemiMVC.Models.Personal
@{
    ViewBag.Title = "PersonalGetir";
    Layout = "~/Views/Shared/_OgrenciLayout.cshtml";
}

<h2 style="margin-top:25px">Personal Listesi</h2>

@using (Html.BeginForm("PersonalGuncelle", "Personal", FormMethod.Post))

{
    <form class="form-group" method="post">
        <div style="margin-bottom: 15px">
            @Html.HiddenFor(y => y.Id)
            @Html.LabelFor(x => x.AdSoyad)
            @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
        </div>
        <div style="margin-bottom: 15px">
            @Html.LabelFor(x => x.Gorevi)
            @Html.TextBoxFor(x => x.Gorevi, new { @class = "form-control" })
        </div>
        <div style="margin-bottom: 15px">
            @Html.LabelFor(x => x.YonetimTip)
            @Html.TextBoxFor(x => x.YonetimTip, new { @class = "form-control" })
        </div>
        <button class="btn btn-success">Güncelle</button>
    </form>
}